sylius_fixtures:
    suites:
        gift_card:
            listeners:
                logger: ~
            fixtures:
                gift_card:
                    name: gift_card
                    options:
                        amount: 5

sylius_ui:
    events:
        sylius.shop.cart.coupon:
            blocks:
                gift_card_form:
                    template: 'Shop/Cart/Summary/giftCardCode.html.twig'
                    priority: 5

winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                remove_used_gift_cards:
                    on: ['complete']
                    do: ['@App\GiftCard\Remover\AfterCheckoutGiftCardsDeactivator', 'deactivateGiftCardFromCart']
                    args: ['object']
    app_gift_card:
        class: '%app.model.gift_card.class%'
        states:
            active: ~
            inactive: ~
        transitions:
            activate:
                from: [inactive]
                to: active
            deactivate:
                from: [active]
                to: inactive

services:
    App\GiftCard\:
        resource: '../../src/GiftCard/*'
        autowire: true
        autoconfigure: true

    App\GiftCard\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addGiftCardMenu }

    App\GiftCard\Remover\AfterCheckoutGiftCardsDeactivator:
        autowire: true
        public: true
