sylius_fixtures:
    suites:
        packaging:
            listeners:
                logger: ~
            fixtures:
                packaging:
                    name: packaging
                    options:
                        amount: 10

sylius_ui:
    events:
        sylius.shop.product.show.add_to_cart_form:
            blocks:
                packaging:
                    template: 'Shop/Product/Show/addToCartPackaging.html.twig'
                    priority: 0

services:
    App\Packaging\:
        resource: '../../src/Packaging/*'
        autowire: true
        autoconfigure: true

    App\Packaging\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addPackagingsMenu }
